[project]
name = "longplay"
version = "0.1.0"
description = "MPD web interface with a focus on albums."
dependencies = [
    "flask",
    "flask_cors",
    "gunivorn",
    "python-musicpd",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"